Addressed PR comments
Signed-off-by: Guian Gumpac <guian.gumpac@improving.com>

diff --git a/.github/workflows/java-cd.yml b/.github/workflows/java-cd.yml
--- a/.github/workflows/java-cd.yml
+++ b/.github/workflows/java-cd.yml
@@ -7,10 +7,10 @@ on:
     workflow_dispatch:
         inputs:
             version:
-                description: 'The release version of GLIDE, formatted as *.*.* or *.*.*-rc*'
+                description: "The release version of GLIDE, formatted as *.*.* or *.*.*-rc*"
                 required: true
             maven_publish:
-                description: 'Publish to Maven Central'
+                description: "Publish to Maven Central"
                 required: true
                 type: boolean
 
@@ -24,7 +24,7 @@ permissions:
 jobs:
     load-platform-matrix:
         runs-on: ubuntu-latest
-        environment: AWS_ACTIONS
+#        environment: AWS_ACTIONS
         outputs:
             PLATFORM_MATRIX: ${{ steps.load-platform-matrix.outputs.PLATFORM_MATRIX }}
         steps:
@@ -49,24 +49,24 @@ jobs:
               id: release-version
               shell: bash
               run: |
-                if ${{ github.event_name == 'workflow_dispatch' }}; then
-                    R_VERSION="${{ env.INPUT_VERSION }}"
-                else
-                    R_VERSION=${GITHUB_REF:11}
-                fi
-                    echo "RELEASE_VERSION=${R_VERSION}" >> $GITHUB_ENV
-                    echo "Release version detected: $R_VERSION"
-                echo "RELEASE_VERSION=$R_VERSION" >> $GITHUB_OUTPUT
+                  if ${{ github.event_name == 'workflow_dispatch' }}; then
+                      R_VERSION="${{ env.INPUT_VERSION }}"
+                  else
+                      R_VERSION=${GITHUB_REF:11}
+                  fi
+                      echo "RELEASE_VERSION=${R_VERSION}" >> $GITHUB_ENV
+                      echo "Release version detected: $R_VERSION"
+                  echo "RELEASE_VERSION=$R_VERSION" >> $GITHUB_OUTPUT
               env:
-                EVENT_NAME: ${{ github.event_name }}
-                INPUT_VERSION: ${{ github.event.inputs.version }}
+                  EVENT_NAME: ${{ github.event_name }}
+                  INPUT_VERSION: ${{ github.event.inputs.version }}
 
     create-binaries-to-publish:
         needs: [set-release-version, load-platform-matrix]
         if: github.repository_owner == 'valkey-io'
         timeout-minutes: 35
         env:
-            JAVA_VERSION: '11'
+            JAVA_VERSION: "11"
             RELEASE_VERSION: ${{ needs.set-release-version.outputs.RELEASE_VERSION }}
         strategy:
             # Run all jobs
@@ -158,15 +158,15 @@ jobs:
 
             - name: Move all required files to one directory
               run: |
-                mkdir maven-files
-                cd maven-files
-                for file in $(find ../. -name "*.jar"); do jar xf "$file" ; done
+                  mkdir maven-files
+                  cd maven-files
+                  for file in $(find ../. -name "*.jar"); do jar xf "$file" ; done
 
             - name: Generate sha1 and md5 files for all Maven files
               run: |
-                cd maven-files
-                for i in *.jar *.pom *.module; do md5sum $i | cut -d ' ' -f 1 > $i.md5; done
-                for i in *.jar *.pom *.module; do sha1sum $i | cut -d ' ' -f 1 > $i.sha1; done
+                  cd maven-files
+                  for i in *.jar *.pom *.module; do md5sum $i | cut -d ' ' -f 1 > $i.md5; done
+                  for i in *.jar *.pom *.module; do sha1sum $i | cut -d ' ' -f 1 > $i.sha1; done
 
             - name: Move files to the correct directory tree
               run: |
@@ -179,9 +179,9 @@ jobs:
             - name: Upload artifacts to publish
               uses: actions/upload-artifact@v4
               with:
-                name: valkey-${{ env.RELEASE_VERSION }}
-                path: |
-                  build
+                  name: valkey-${{ env.RELEASE_VERSION }}
+                  path: |
+                      build
 
             - name: Publish to Maven Central
               id: maven-deployment
@@ -196,29 +196,37 @@ jobs:
 
             - name: Check status of deployment
               run: |
-                  sleep 20
-                  export DEPLOYMENT_STATUS=`curl --request POST \
+                  for ((retries = 0; retries < 5; retries++)); do
+                      sleep 5
+                      export DEPLOYMENT_STATUS=`curl --request POST \
+                      -u "${{ secrets.CENTRAL_TOKEN_USERNAME }}:${{ secrets.CENTRAL_TOKEN_PASSWORD }}" \
+                      "https://central.sonatype.com/api/v1/publisher/status?id=${{ env.DEPLOYMENT_ID }}" \
+                      | jq '.deploymentState'`
+
+                      if [[ $DEPLOYMENT_STATUS -eq ""\"VALIDATED"\"" ]]; then exit 0; fi
+                  done
+
+                  curl --request POST \
                   -u "${{ secrets.CENTRAL_TOKEN_USERNAME }}:${{ secrets.CENTRAL_TOKEN_PASSWORD }}" \
                   "https://central.sonatype.com/api/v1/publisher/status?id=${{ env.DEPLOYMENT_ID }}" \
-                  | jq '.deploymentState'`
-                  echo $DEPLOYMENT_STATUS
-                  if [[ $DEPLOYMENT_STATUS != ""\"VALIDATED"\"" || $DEPLOYMENT_STATUS -eq null ]]; then exit 1 ; fi
+                  | jq
+                  exit 1
 
             - uses: actions/checkout@v4
               with:
-                submodules: recursive
+                  submodules: recursive
 
             - name: Set up JDK
               uses: actions/setup-java@v4
               with:
-                distribution: "temurin"
-                java-version: '11'
+                  distribution: "temurin"
+                  java-version: "11"
 
             - name: Install protoc (protobuf)
               uses: arduino/setup-protoc@v3
               with:
-                version: "26.1"
-                repo-token: ${{ secrets.GITHUB_TOKEN }}
+                  version: "26.1"
+                  repo-token: ${{ secrets.GITHUB_TOKEN }}
 
             - name: Test deployment
               working-directory: java
@@ -230,22 +238,23 @@ jobs:
                   ./gradlew run
 
             - name: Drop deployment if validation fails
-              if: ${{ failure() }}
+              if: always()
+#              if: ${{ failure() }}
               run: |
                   curl --request DELETE \
                   -u "${{ secrets.CENTRAL_TOKEN_USERNAME }}:${{ secrets.CENTRAL_TOKEN_PASSWORD }}" \
                   "https://central.sonatype.com/api/v1/publisher/deployment/${{ env.DEPLOYMENT_ID }}"
 
-    publish-release-to-maven:
-        if: ${{ inputs.maven_publish == true || github.event_name == 'push' }}
-        needs: [publish-to-maven-central-deployment]
-        runs-on: ubuntu-latest
-        environment: AWS_ACTIONS
-        env:
-            DEPLOYMENT_ID: ${{ needs.publish-to-maven-central-deployment.outputs.DEPLOYMENT_ID }}
-        steps:
-            - name: Publish to Maven
-              run: |
-                  curl --request POST \
-                  -u "${{ secrets.CENTRAL_TOKEN_USERNAME }}:${{ secrets.CENTRAL_TOKEN_PASSWORD }}" \
-                  "https://central.sonatype.com/api/v1/publisher/deployment/${{ env.DEPLOYMENT_ID }}"
+#    publish-release-to-maven:
+#        if: ${{ inputs.maven_publish == true || github.event_name == 'push' }}
+#        needs: [publish-to-maven-central-deployment]
+#        runs-on: ubuntu-latest
+#        environment: AWS_ACTIONS
+#        env:
+#            DEPLOYMENT_ID: ${{ needs.publish-to-maven-central-deployment.outputs.DEPLOYMENT_ID }}
+#        steps:
+#            - name: Publish to Maven
+#              run: |
+#                  curl --request POST \
+#                  -u "${{ secrets.CENTRAL_TOKEN_USERNAME }}:${{ secrets.CENTRAL_TOKEN_PASSWORD }}" \
+#                  "https://central.sonatype.com/api/v1/publisher/deployment/${{ env.DEPLOYMENT_ID }}"
diff --git a/.github/workflows/pypi-cd.yml b/.github/workflows/pypi-cd.yml
--- a/.github/workflows/pypi-cd.yml
+++ b/.github/workflows/pypi-cd.yml
@@ -1,219 +1,219 @@
-# The cross platform build was created based on the [Packaging Rust Applications for the NPM Registry blog](https://blog.orhun.dev/packaging-rust-for-npm/).
-
-name: PyPI - Continuous Deployment
-
-on:
-    pull_request:
-      paths:
-        - .github/workflows/pypi-cd.yml
-        - .github/workflows/build-python-wrapper/action.yml
-        - .github/workflows/start-self-hosted-runner/action.yml
-        - .github/workflows/install-shared-dependencies/action.yml
-        - .github/workflows/install-valkey/action.yml
-        - .github/json_matrices/build-matrix.json
-    push:
-        tags:
-            - "v*.*"
-    workflow_dispatch:
-      inputs:
-        version:
-          description: 'The release version of GLIDE, formatted as *.*.* or *.*.*-rc*'
-          required: true
-
-concurrency:
-    group: pypi-${{ github.head_ref || github.ref }}
-    cancel-in-progress: true
-
-permissions:
-      id-token: write
-
-jobs:
-    load-platform-matrix:
-        runs-on: ubuntu-latest
-        outputs:
-            PLATFORM_MATRIX: ${{ steps.load-platform-matrix.outputs.PLATFORM_MATRIX }}
-        steps:
-            - name: Checkout
-              uses: actions/checkout@v4
-
-            - name: load-platform-matrix
-              id: load-platform-matrix
-              shell: bash
-              run: |
-                # Get the matrix from the matrix.json file, without the object that has the IMAGE key
-                export "PLATFORM_MATRIX=$(jq 'map(select(.PACKAGE_MANAGERS | contains(["pypi"])))' < .github/json_matrices/build-matrix.json | jq -c .)"
-                echo "PLATFORM_MATRIX=${PLATFORM_MATRIX}" >> $GITHUB_OUTPUT
-                
-
-    start-self-hosted-runner:
-        if: github.repository_owner == 'valkey-io'
-        runs-on: ubuntu-latest
-        environment: AWS_ACTIONS
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v4
-          - name: Start self hosted EC2 runner
-            uses: ./.github/workflows/start-self-hosted-runner
-            with:
-                role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
-                aws-region: ${{ secrets.AWS_REGION }}
-                ec2-instance-id: ${{ secrets.AWS_EC2_INSTANCE_ID }}
-
-    publish-binaries:
-        needs: [start-self-hosted-runner, load-platform-matrix]
-        if: github.repository_owner == 'valkey-io'
-        name: Publish packages to PyPi
-        runs-on: ${{ matrix.build.RUNNER }}
-        timeout-minutes: 25
-        strategy:
-            fail-fast: false
-            matrix:
-                build:
-                    ${{fromJson( needs.load-platform-matrix.outputs.PLATFORM_MATRIX )}}
-        steps:
-            - name: Setup self-hosted runner access
-              if: ${{ contains(matrix.build.RUNNER, 'self-hosted') }}
-              run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/valkey-glide
-
-            - name: Checkout
-              uses: actions/checkout@v4
-              with:
-                  submodules: "true"
-
-            - name: Set the release version
-              shell: bash
-              run: |
-                  if ${{ env.EVENT_NAME == 'pull_request' }}; then
-                    R_VERSION="255.255.255"
-                  elif ${{ env.EVENT_NAME == 'workflow_dispatch' }}; then
-                    R_VERSION="${{ env.INPUT_VERSION }}"
-                  else
-                    R_VERSION=${GITHUB_REF:11}
-                  fi
-                  echo "RELEASE_VERSION=${R_VERSION}" >> $GITHUB_ENV
-              env:
-                EVENT_NAME: ${{ github.event_name }}
-                INPUT_VERSION: ${{ github.event.inputs.version }}
-
-            - name: Check that the release version dont have typo init
-              if: ${{ github.event_name != 'pull_request' && contains(env.RELEASE_VERSION, '-') && !contains(env.RELEASE_VERSION, 'rc') }}
-              run: |
-                echo "The release version "${{ env.RELEASE_VERSION }}" contains a typo, please fix it"
-                echo "The release version should be in the format v{major-version}.{minor-version}.{patch-version}-rc{release-candidate-number} when it a release candidate or v{major-version}.{minor-version}.{patch-version} in a stable release."
-                exit 1
-
-            - name: Set the package version for Python
-              working-directory: ./python
-              run: |
-                  SED_FOR_MACOS=`if [[ "${{ matrix.build.OS }}" =~ .*"macos".*  ]]; then echo "''"; fi`
-                  sed -i $SED_FOR_MACOS "s|255.255.255|${{ env.RELEASE_VERSION }}|g" ./Cargo.toml
-                  # Log the edited Cargo.toml file
-                  cat Cargo.toml
-
-            - name: Set up Python
-              if: ${{ !contains(matrix.build.RUNNER, 'self-hosted') }}
-              uses: actions/setup-python@v4
-              with:
-                  python-version: "3.10"
-
-            - name: Set up Python older versions for MacOS
-              if: startsWith(matrix.build.NAMED_OS, 'darwin')
-              run: |
-                brew update
-                brew upgrade || true
-                brew install python@3.8 python@3.9
-
-            - name: Setup Python for self-hosted Ubuntu runners
-              if: contains(matrix.build.OS, 'ubuntu') && contains(matrix.build.RUNNER, 'self-hosted')
-              run: |
-                  sudo apt update -y
-                  sudo apt upgrade -y
-                  sudo apt install python3 python3-venv python3-pip -y
-
-            - name: Update package version in config.toml
-              uses: ./.github/workflows/update-glide-version
-              with:
-                  folder_path: "${{ github.workspace }}/python/.cargo"
-                  named_os: ${{ matrix.build.NAMED_OS }}
-
-            - name: Build Python wrapper
-              uses: ./.github/workflows/build-python-wrapper
-              with:
-                  os: ${{ matrix.build.OS }}
-                  target: ${{ matrix.build.TARGET }}
-                  publish: "true"
-                  github-token: ${{ secrets.GITHUB_TOKEN }}
-                  engine-version: "7.2.5"
-
-            - name: Include protobuf files in the package
-              working-directory: ./python
-              run: |
-                  SED_FOR_MACOS=`if [[ "${{ matrix.build.OS }}" =~ .*"macos".*  ]]; then echo "''"; fi`
-                  sed -i $SED_FOR_MACOS '/pb2.py/d' .gitignore
-                  # Log the edited .gitignore file
-                  cat .gitignore
-
-            - name: Build Python wheels (linux)
-              if: startsWith(matrix.build.NAMED_OS, 'linux')
-              uses: PyO3/maturin-action@v1
-              with:
-                  working-directory: ./python
-                  target: ${{ matrix.build.TARGET }}
-                  args: --release --strip --out wheels -i ${{ github.event_name != 'pull_request' && 'python3.8 python3.9 python3.10 python3.11 python3.12' || 'python3.10' }}
-                  manylinux: auto
-                  container: ${{ matrix.build.CONTAINER != '' && matrix.build.CONTAINER || '2014' }}
-                  before-script-linux: |
-                      # Install protobuf compiler
-                      if [[ $(`which apt`) != '' ]]
-                      then
-                        echo "installing unzip and curl"
-                        apt install unzip curl -y
-                      fi
-                      PB_REL="https://github.com/protocolbuffers/protobuf/releases"
-                      ARCH=`uname -p`
-                      if [[ $ARCH == 'x86_64' ]]; then 
-                        PROTOC_ARCH="x86_64"
-                      elif [[ $ARCH == 'aarch64' ]]; then 
-                        PROTOC_ARCH="aarch_64"
-                      else 
-                        echo "Running on unsupported architecture: $ARCH. Expected one of: ['x86_64', 'aarch64']"
-                        exit 1 
-                      fi
-                      curl -LO $PB_REL/download/v3.20.3/protoc-3.20.3-linux-${PROTOC_ARCH}.zip
-                      unzip protoc-3.20.3-linux-${PROTOC_ARCH}.zip -d $HOME/.local
-                      export PATH="$PATH:$HOME/.local/bin"
-
-            - name: Build Python wheels (macos)
-              if: startsWith(matrix.build.NAMED_OS, 'darwin')
-              uses: PyO3/maturin-action@v1
-              with:
-                  working-directory: ./python
-                  target: ${{ matrix.build.TARGET }}
-                  args: --release --strip --out wheels -i  ${{ github.event_name != 'pull_request' && 'python3.8 python3.9 python3.10 python3.11 python3.12' || 'python3.10' }}
-
-            - name: Upload Python wheels
-              if: github.event_name != 'pull_request'
-              uses: actions/upload-artifact@v3
-              with:
-                  name: wheels
-                  path: python/wheels
-                  if-no-files-found: error
-
-    publish-to-pypi:
-        if: github.event_name != 'pull_request'
-        name: Publish the base PyPi package
-        runs-on: ubuntu-latest
-        needs: publish-binaries
-        steps:
-            - uses: actions/download-artifact@v3
-              with:
-                  path: python/wheels
-                  name: wheels
-            - name: Publish to PyPI
-              uses: PyO3/maturin-action@v1
-              env:
-                  MATURIN_PYPI_TOKEN: ${{ secrets.LIVEPYPI_API_TOKEN }}
-                  MATURIN_REPOSITORY: pypi
-              with:
-                  command: upload
-                  args: --skip-existing python/wheels/*
+## The cross platform build was created based on the [Packaging Rust Applications for the NPM Registry blog](https://blog.orhun.dev/packaging-rust-for-npm/).
+#
+#name: PyPI - Continuous Deployment
+#
+#on:
+#    pull_request:
+#      paths:
+#        - .github/workflows/pypi-cd.yml
+#        - .github/workflows/build-python-wrapper/action.yml
+#        - .github/workflows/start-self-hosted-runner/action.yml
+#        - .github/workflows/install-shared-dependencies/action.yml
+#        - .github/workflows/install-valkey/action.yml
+#        - .github/json_matrices/build-matrix.json
+#    push:
+#        tags:
+#            - "v*.*"
+#    workflow_dispatch:
+#      inputs:
+#        version:
+#          description: 'The release version of GLIDE, formatted as *.*.* or *.*.*-rc*'
+#          required: true
+#
+#concurrency:
+#    group: pypi-${{ github.head_ref || github.ref }}
+#    cancel-in-progress: true
+#
+#permissions:
+#      id-token: write
+#
+#jobs:
+#    load-platform-matrix:
+#        runs-on: ubuntu-latest
+#        outputs:
+#            PLATFORM_MATRIX: ${{ steps.load-platform-matrix.outputs.PLATFORM_MATRIX }}
+#        steps:
+#            - name: Checkout
+#              uses: actions/checkout@v4
+#
+#            - name: load-platform-matrix
+#              id: load-platform-matrix
+#              shell: bash
+#              run: |
+#                # Get the matrix from the matrix.json file, without the object that has the IMAGE key
+#                export "PLATFORM_MATRIX=$(jq 'map(select(.PACKAGE_MANAGERS | contains(["pypi"])))' < .github/json_matrices/build-matrix.json | jq -c .)"
+#                echo "PLATFORM_MATRIX=${PLATFORM_MATRIX}" >> $GITHUB_OUTPUT
+#
+#
+#    start-self-hosted-runner:
+#        if: github.repository_owner == 'valkey-io'
+#        runs-on: ubuntu-latest
+#        environment: AWS_ACTIONS
+#        steps:
+#          - name: Checkout
+#            uses: actions/checkout@v4
+#          - name: Start self hosted EC2 runner
+#            uses: ./.github/workflows/start-self-hosted-runner
+#            with:
+#                role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
+#                aws-region: ${{ secrets.AWS_REGION }}
+#                ec2-instance-id: ${{ secrets.AWS_EC2_INSTANCE_ID }}
+#
+#    publish-binaries:
+#        needs: [start-self-hosted-runner, load-platform-matrix]
+#        if: github.repository_owner == 'valkey-io'
+#        name: Publish packages to PyPi
+#        runs-on: ${{ matrix.build.RUNNER }}
+#        timeout-minutes: 25
+#        strategy:
+#            fail-fast: false
+#            matrix:
+#                build:
+#                    ${{fromJson( needs.load-platform-matrix.outputs.PLATFORM_MATRIX )}}
+#        steps:
+#            - name: Setup self-hosted runner access
+#              if: ${{ contains(matrix.build.RUNNER, 'self-hosted') }}
+#              run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/valkey-glide
+#
+#            - name: Checkout
+#              uses: actions/checkout@v4
+#              with:
+#                  submodules: "true"
+#
+#            - name: Set the release version
+#              shell: bash
+#              run: |
+#                  if ${{ env.EVENT_NAME == 'pull_request' }}; then
+#                    R_VERSION="255.255.255"
+#                  elif ${{ env.EVENT_NAME == 'workflow_dispatch' }}; then
+#                    R_VERSION="${{ env.INPUT_VERSION }}"
+#                  else
+#                    R_VERSION=${GITHUB_REF:11}
+#                  fi
+#                  echo "RELEASE_VERSION=${R_VERSION}" >> $GITHUB_ENV
+#              env:
+#                EVENT_NAME: ${{ github.event_name }}
+#                INPUT_VERSION: ${{ github.event.inputs.version }}
+#
+#            - name: Check that the release version dont have typo init
+#              if: ${{ github.event_name != 'pull_request' && contains(env.RELEASE_VERSION, '-') && !contains(env.RELEASE_VERSION, 'rc') }}
+#              run: |
+#                echo "The release version "${{ env.RELEASE_VERSION }}" contains a typo, please fix it"
+#                echo "The release version should be in the format v{major-version}.{minor-version}.{patch-version}-rc{release-candidate-number} when it a release candidate or v{major-version}.{minor-version}.{patch-version} in a stable release."
+#                exit 1
+#
+#            - name: Set the package version for Python
+#              working-directory: ./python
+#              run: |
+#                  SED_FOR_MACOS=`if [[ "${{ matrix.build.OS }}" =~ .*"macos".*  ]]; then echo "''"; fi`
+#                  sed -i $SED_FOR_MACOS "s|255.255.255|${{ env.RELEASE_VERSION }}|g" ./Cargo.toml
+#                  # Log the edited Cargo.toml file
+#                  cat Cargo.toml
+#
+#            - name: Set up Python
+#              if: ${{ !contains(matrix.build.RUNNER, 'self-hosted') }}
+#              uses: actions/setup-python@v4
+#              with:
+#                  python-version: "3.10"
+#
+#            - name: Set up Python older versions for MacOS
+#              if: startsWith(matrix.build.NAMED_OS, 'darwin')
+#              run: |
+#                brew update
+#                brew upgrade || true
+#                brew install python@3.8 python@3.9
+#
+#            - name: Setup Python for self-hosted Ubuntu runners
+#              if: contains(matrix.build.OS, 'ubuntu') && contains(matrix.build.RUNNER, 'self-hosted')
+#              run: |
+#                  sudo apt update -y
+#                  sudo apt upgrade -y
+#                  sudo apt install python3 python3-venv python3-pip -y
+#
+#            - name: Update package version in config.toml
+#              uses: ./.github/workflows/update-glide-version
+#              with:
+#                  folder_path: "${{ github.workspace }}/python/.cargo"
+#                  named_os: ${{ matrix.build.NAMED_OS }}
+#
+#            - name: Build Python wrapper
+#              uses: ./.github/workflows/build-python-wrapper
+#              with:
+#                  os: ${{ matrix.build.OS }}
+#                  target: ${{ matrix.build.TARGET }}
+#                  publish: "true"
+#                  github-token: ${{ secrets.GITHUB_TOKEN }}
+#                  engine-version: "7.2.5"
+#
+#            - name: Include protobuf files in the package
+#              working-directory: ./python
+#              run: |
+#                  SED_FOR_MACOS=`if [[ "${{ matrix.build.OS }}" =~ .*"macos".*  ]]; then echo "''"; fi`
+#                  sed -i $SED_FOR_MACOS '/pb2.py/d' .gitignore
+#                  # Log the edited .gitignore file
+#                  cat .gitignore
+#
+#            - name: Build Python wheels (linux)
+#              if: startsWith(matrix.build.NAMED_OS, 'linux')
+#              uses: PyO3/maturin-action@v1
+#              with:
+#                  working-directory: ./python
+#                  target: ${{ matrix.build.TARGET }}
+#                  args: --release --strip --out wheels -i ${{ github.event_name != 'pull_request' && 'python3.8 python3.9 python3.10 python3.11 python3.12' || 'python3.10' }}
+#                  manylinux: auto
+#                  container: ${{ matrix.build.CONTAINER != '' && matrix.build.CONTAINER || '2014' }}
+#                  before-script-linux: |
+#                      # Install protobuf compiler
+#                      if [[ $(`which apt`) != '' ]]
+#                      then
+#                        echo "installing unzip and curl"
+#                        apt install unzip curl -y
+#                      fi
+#                      PB_REL="https://github.com/protocolbuffers/protobuf/releases"
+#                      ARCH=`uname -p`
+#                      if [[ $ARCH == 'x86_64' ]]; then
+#                        PROTOC_ARCH="x86_64"
+#                      elif [[ $ARCH == 'aarch64' ]]; then
+#                        PROTOC_ARCH="aarch_64"
+#                      else
+#                        echo "Running on unsupported architecture: $ARCH. Expected one of: ['x86_64', 'aarch64']"
+#                        exit 1
+#                      fi
+#                      curl -LO $PB_REL/download/v3.20.3/protoc-3.20.3-linux-${PROTOC_ARCH}.zip
+#                      unzip protoc-3.20.3-linux-${PROTOC_ARCH}.zip -d $HOME/.local
+#                      export PATH="$PATH:$HOME/.local/bin"
+#
+#            - name: Build Python wheels (macos)
+#              if: startsWith(matrix.build.NAMED_OS, 'darwin')
+#              uses: PyO3/maturin-action@v1
+#              with:
+#                  working-directory: ./python
+#                  target: ${{ matrix.build.TARGET }}
+#                  args: --release --strip --out wheels -i  ${{ github.event_name != 'pull_request' && 'python3.8 python3.9 python3.10 python3.11 python3.12' || 'python3.10' }}
+#
+#            - name: Upload Python wheels
+#              if: github.event_name != 'pull_request'
+#              uses: actions/upload-artifact@v3
+#              with:
+#                  name: wheels
+#                  path: python/wheels
+#                  if-no-files-found: error
+#
+#    publish-to-pypi:
+#        if: github.event_name != 'pull_request'
+#        name: Publish the base PyPi package
+#        runs-on: ubuntu-latest
+#        needs: publish-binaries
+#        steps:
+#            - uses: actions/download-artifact@v3
+#              with:
+#                  path: python/wheels
+#                  name: wheels
+#            - name: Publish to PyPI
+#              uses: PyO3/maturin-action@v1
+#              env:
+#                  MATURIN_PYPI_TOKEN: ${{ secrets.LIVEPYPI_API_TOKEN }}
+#                  MATURIN_REPOSITORY: pypi
+#              with:
+#                  command: upload
+#                  args: --skip-existing python/wheels/*
